<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        window.onerror = function (message, url, line, col, error) {
            console.log(`${message}\n At ${line}:${col} of ${url}`);
        };
        function readData() {
            badFunc(); // 啊，出问题了！
        }
        window.addEventListener('unhandledrejection', function (event) {
            // 这个事件对象有两个特殊的属性：
            console.log(event.promise); // [object Promise] —— 生成该全局 error 的 promise
            console.log(event.reason); // Error: Whoops! —— 未处理的 error 对象
        });
    </script>
    <script src="./try.js" ></script>
</body>

</html>